# Uncomment the next line to define a global platform for your project
platform :ios, '18.0'

target 'StaticViewDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Masonry'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # 确保所有的 Pod 目标都使用 iOS 11.0 或更高版本
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'
    end
  end
end
